### ISSUE TITLE
No proper license

### ISSUE THREAD

**Issue by informarte** [MiniZinc/minizinc-benchmarks#5]
There are legal systems (for example in the US and in the EU) where copyright sticks to authors and just declaring that something is in the public domain is not enough to facilitate safe re-use (without accidental copyright infringement), see https://en.wikipedia.org/wiki/Public_domain#Dedicating_works_to_the_public_domain. In my understanding, the only reliable way for donors to work around their copyright is to provide a suitable license. For example, minizinc-examples are issued under the MIT license and hence it is safe to re-use, modify, and redistribute them.

**Comment by guidotack** [comment]
Good point, thanks.
